<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>SIPlus</Title>
    <Version>$(VersionPrefix)1.1.0</Version>
    <Authors>PortraitExpress;Payton-Doud</Authors>
    <Description>SIPlus String Templating Library Bindings for .NET</Description>
    <PackageProjectUrl>https://github.com/Portrait-Express/SIPlus.NET</PackageProjectUrl>
    <PackageTags>template;utility;string;text</PackageTags>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <Company>PortraitExpress</Company>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Portrait-Express/SIPlus.NET</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="runtimes\linux-x64\native\libsiplus.so" Pack="True" PackagePath="runtimes\linux-x64\native\libsiplus.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
	  <None Update="runtimes\linux-x86\native\libsiplus.so" Pack="True" PackagePath="runtimes\linux-x86\native\libsiplus.so">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
    <None Update="runtimes\win-x64\native\siplus.dll" Pack="True" PackagePath="runtimes\win-x64\native\siplus.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x86\native\siplus.dll" Pack="True" PackagePath="runtimes\win-x86\native\siplus.dll">
  	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
	<None Update="runtimes\browser-wasm\native\siplus.a" Pack="True" PackagePath="runtimes\browser-wasm\native\siplus.a">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
	<None Update="buildTransitive\SIPlus.NET.targets" Pack="True" PackagePath="buildTransitive\SIPlus.NET.targets">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
  </ItemGroup>
</Project>
