<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>SIPlus</Title>
    <Version>$(VersionPrefix)1.0.0</Version>
    <Authors>$(AssemblyName)</Authors>
    <Description>SIPlus String Templating Library Bindings for .NET</Description>
    <PackageProjectUrl>https://github.com/Portrait-Express/SIPlus.NET</PackageProjectUrl>
    <PackageTags>template;utility;string;text</PackageTags>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <None Update="runtimes\linux-x64\native\libsiplus.so" Pack="True" PackagePath="runtimes\linux-x64\native\libsiplus.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\siplus.dll" Pack="True" PackagePath="runtimes\win-x64\native\siplus.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
	  <None Update="runtimes\win-x86\native\siplus.dll" Pack="True" PackagePath="runtimes\win-x86\native\siplus.dll">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
  </ItemGroup>
</Project>
